### ISSUE TITLE
Not working with Arduino 1.0

### ISSUE THREAD

**Issue by hurik** [davidhbrown/RealTimeClockDS1307#1]
Hi,

will there be an update for Arduino 1.0?

Thanks for you efforts.

hurik

**Comment by davidhbrown** [comment]
Thanks for your interest! I'd be happy to look at updating the code for Arduino 1.0. However, the only DS1307 I have is now embedded in a data logger in the field. I could test whether updated code compiles. Do you have the necessary hardware to make sure it actually works?

**Comment by hurik** [comment]
yes, i have the hardware and i would be happy to test it.

**Comment by davidhbrown** [comment]
Okay, I have something that will compile now... had to change three sorts of thing. Using write() instead of send() / read() instead of receive(); had to get the type definitions from a new Arduino.h file; and had to work around a function overloading confusion in classes that extend print. 

Now I guess I have to re-install git... I actually uninstalled it just the day before your email because I hadn't used it since uploading this!

**Comment by hurik** [comment]
hi, i get it running. :)

i make the same changes, but i always got the error: call of overloaded 'write(int)' is ambiguous

it is an error in the wire library. you have to add this lines at the end of the wire.h before the "using Print::write;":
    inline size_t write(unsigned long n) { return write((uint8_t)n); }
    inline size_t write(long n) { return write((uint8_t)n); }
    inline size_t write(unsigned int n) { return write((uint8_t)n); }
    inline size_t write(int n) { return write((uint8_t)n); }

should be fixed in the next version. more infos here: http://code.google.com/p/arduino/issues/detail?id=527

**Comment by davidhbrown** [comment]
Sorry I haven't had time to get git up and running and upload the modification code (it's the end of term where I'm teaching a PHP course).  I put a cast in the call to the functions rather than changing wire.h as I saw posted somewhere when I googled the error. Should still work with the updated version.

Should I email you the files directly? Or would you like to add yours into the repository if you're more git-enabled than I?

## 

David H. Brown
dave@davidhbrown.us

-----Original Message-----

**Comment by hurik** [comment]
i will try to upload it.

**Comment by hurik** [comment]
hi,

i tested your code and it is working fine. it is also working fine with the original wire.h from arduino 1.0.

can you give me the rights to upload changes in this repo? you must add me as a collaborator under admin in the repo.

thank you very much an bye,
Andreas

**Comment by davidhbrown** [comment]
I think I got you added; thanks so much for your help!

**Comment by hurik** [comment]
ok, new version is uploaded.
